"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 18:21:23.887111
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_photos', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('deleted_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_id'), ['id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('dhash', sa.String(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('lens_model', sa.String(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_altitude', sa.Float(), nullable=True),
    sa.Column('has_thumb', sa.Boolean(), nullable=True),
    sa.Column('has_web', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_date_taken'), ['date_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_dhash'), ['dhash'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_phash'), ['phash'], unique=False)

    op.create_table('similar_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('group_type', sa.String(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('selected_photo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('similar_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_similar_groups_id'), ['id'], unique=False)

    op.create_table('photo_similar_groups',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['similar_groups.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_similar_groups')
    with op.batch_alter_table('similar_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_similar_groups_id'))

    op.drop_table('similar_groups')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_phash'))
        batch_op.drop_index(batch_op.f('ix_photos_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_photos_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_photos_id'))
        batch_op.drop_index(batch_op.f('ix_photos_filename'))
        batch_op.drop_index(batch_op.f('ix_photos_dhash'))
        batch_op.drop_index(batch_op.f('ix_photos_date_taken'))

    op.drop_table('photos')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_id'))

    op.drop_table('folders')
    # ### end Alembic commands ###
